FROM ubuntu:plucky

# Install some basics for Ubuntu (curl, gdb, git, apt, nasm)
RUN apt update && apt -y upgrade && apt install -y curl software-properties-common locales gdb git nasm

# Install some common dependencies (openssl, uuid, libcurl, boost)
RUN apt -y install make openssl libssl-dev uuid-dev libcurl4-openssl-dev libboost-all-dev

# Install gcc-15 (latest)
RUN add-apt-repository ppa:ubuntu-toolchain-r/test 
RUN apt update && apt -y install gcc-15 g++-15

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV LC_COLLATE=C
